"""Egress policy v1 (PLAN.md Phase 2): default-deny with a domain allowlist.

Local Docker realization: the sandbox joins an *internal* Docker network (no
route out), and a squid sidecar sits on both that network and the default
bridge. Everything in the sandbox that wants the internet must go through
`http://<alias>:3128`, which only CONNECTs/fetches allowlisted domains. The
proxy address is handed to the sandbox via HTTP_PROXY/HTTPS_PROXY env, which
pip, npm, git-over-https and litellm all honor.

This is policy-of-record, not a jailproof boundary (a hostile engine could
ignore the env — production substrates enforce at the VPC layer instead;
ARCHITECTURE.md §9). It exists so that accidental egress fails closed and the
allowlist is exercised from day one.
"""

from dataclasses import dataclass, field

PROXY_ALIAS = "agentx-egress-proxy"
PROXY_PORT = 3128

DEFAULT_ALLOWED_DOMAINS: tuple[str, ...] = (
    # model providers
    ".api.openai.com",
    ".api.anthropic.com",
    ".generativelanguage.googleapis.com",
    # package registries
    ".pypi.org",
    ".files.pythonhosted.org",
    ".registry.npmjs.org",
    # source + release assets (.github.com covers codeload/api subdomains)
    ".github.com",
    ".objects.githubusercontent.com",
    ".raw.githubusercontent.com",
    ".ghcr.io",
)


@dataclass
class EgressPolicy:
    mode: str = "allowlist"  # "allowlist" (default-deny) | "open" (dev only)
    allowed_domains: tuple[str, ...] = field(default=DEFAULT_ALLOWED_DOMAINS)

    def proxy_env(self) -> dict[str, str]:
        if self.mode != "allowlist":
            return {}
        url = f"http://{PROXY_ALIAS}:{PROXY_PORT}"
        return {
            "HTTP_PROXY": url,
            "HTTPS_PROXY": url,
            "http_proxy": url,
            "https_proxy": url,
            "NO_PROXY": "localhost,127.0.0.1",
        }

    def squid_conf(self) -> str:
        domains = " ".join(self.allowed_domains)
        return f"""# generated by AgentX — default-deny egress allowlist
http_port {PROXY_PORT}
acl allowed_dst dstdomain {domains}
acl SSL_ports port 443
acl Safe_ports port 80 443
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow allowed_dst
http_access deny all
# stdio:/dev/stdout is unwritable once squid drops privileges; denials still
# surface in the container log via -d 1
access_log none
cache deny all
"""
